baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'claire freehafer'
sectionPagesMenu = 'main'
disableKinds = ['rss']
capitalizeListTitles = false
[taxonomies]
  tag = 'tags'
  ingredient = 'ingredients'
[Params]
  photographyApiPath = ''
[module]
  [[module.mounts]]
    excludeFiles = ['photography/*', 'components/*']
    source = 'content'
    target = 'content'
  [[module.mounts]]
    source = 'content/ingredients'
    target = 'content/recipes/ingredients'
  [[module.mounts]]
    source = 'content/tags'
    target = 'content/lists/tags'
[permalinks.term]
  ingredients = 'recipes/ingredients/:title'
  tags = 'lists/tags/:title'