baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'claire freehafer'
disableKinds = ['rss']
capitalizeListTitles = false
[taxonomies]
  tag = 'tags'
  ingredient = 'ingredients'
[Params]
  photographyApiPath = ''
[module]
  [[module.mounts]]
    excludeFiles = ['photography/*', 'components/*']
    source = 'content'
    target = 'content'
[permalinks.section]
  'animal-crossing' = 'video-games/animal-crossing/'
[permalinks.term]
  ingredients = 'recipes/ingredients/:title'
  tags = 'lists/tags/:title'