baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'claire freehafer'
disableKinds = ['rss']
capitalizeListTitles = false
[taxonomies]
  tag = 'tags'
  ingredient = 'ingredients'
[Params]
  photographyApiPath = ''
[permalinks.section]
  animal-crossing = 'video-games/animal-crossing'
  the-witness = 'video-games/the-witness'
  uncharted-4 = 'video-games/uncharted-4'
[permalinks.term]
  ingredients = 'recipes/ingredients/:title'
  tags = 'lists/tags/:title'