baseURL = 'https://clairefreehafer.neocities.org/'
languageCode = 'en-us'
title = 'claire freehafer'
sectionPagesMenu = 'main'
disableKinds = ['rss']
capitalizeListTitles = false
[taxonomies]
  tag = 'tags'
  ingredient = 'ingredients'
[module]
  [[module.mounts]]
    excludeFiles = ['photography/*', 'components/*']
    source = 'content'
    target = 'content'
